#!/bin/bash
daemon_name=samen

. /etc/rc.conf
. /etc/rc.d/functions

. /etc/conf.d/$daemon_name

case "$1" in
  start)
    stat_busy "Starting $daemon_name"
    ps ax | grep wpa_supplicant | grep $INTERFACE | grep -v grep > /dev/null 2>&1
    if [ $? -eq 0 ] ; then
      stat_die
      exit 1
    fi
    ifconfig $INTERFACE up > /dev/null 2>&1
    wpa_supplicant -D$DRIVER -i$INTERFACE -c$CONFIG_FILE $EXTRA_ARGS -B > /dev/null 2>&1
    wpa_cli -B -a /usr/sbin/samen-handler > /dev/null 2>&1
    if [ $? -gt 0 ]; then
      stat_die
    else
      add_daemon $daemon_name
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping $daemon_name"
    killall wpa_supplicant > /dev/null 2>&1
    if [ $? -gt 0 ]; then
      stat_die
    else
      ifconfig $INTERFACE down > /dev/null 2>&1
      rm_daemon $daemon_name
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
